feat: include the default extrinsics on the latest blocks list
LimeChain/polkadot-devground-client pull request #113
Opened 2024-10-22 14:46 UTC by AlexanderDrazhev

This update ensures that default extrinsics are now included when displaying blocks in the latest blocks scroll area.

2024-10-24 11:22 UTC, DimitarTAtanasov commented on src/views/explorer/components/extrinsicsList/index.tsx
> -      .flatMap((block) => block?.extrinsics ?? [])
There is one more route `explorer/extrinsics` where want to filter out the first two extrinsics of each block

2024-10-24 11:23 UTC, DimitarTAtanasov requested changes
There is one more route `explorer/extrinsics` where want to filter out the first two extrinsics of each block

2024-10-24 13:36 UTC, AlexanderDrazhev commented
> There is one more route `explorer/extrinsics` where want to filter out the first two extrinsics of each block

Done

2024-10-25 12:18 UTC, DimitarTAtanasov approved these changes

2024-10-25 13:18 UTC, merged