Signed extrinsics
LimeChain/polkadot-devground-client pull request #53
Opened 2024-08-27 15:38 UTC by Denis-Dinkov

2024-08-28 13:42 UTC, DimitarTAtanasov requested changes

2024-08-28 13:42 UTC, DimitarTAtanasov commented on src/assets/styles/index.css
> +.explorer-pages-table {
Could we think of moving this or renaming it considering the place it is defined

2024-08-28 13:42 UTC, DimitarTAtanasov commented on src/views/signedExtrinsics/index.tsx
> +  const loadInitialData = useCallback(() => {
Maybe we could think of refactor the way we are getting the extrinsics list, as it is now being used on multiple places and iterating the whole structure in each component could eventually lead to lack of performance.

2024-09-01 09:52 UTC, pivanov reviewed
I think we can make this one better:
`src/components/chainDataList/index.tsx`
There are a lot of components with a lot of useEffects ... 

Also you can check branch `signed-extrinsics-small-improvements` to see some improvements related to modal

2024-09-01 09:52 UTC, pivanov commented on src/components/modals/modalShowJson/index.tsx
> +      <h5 className="self-start font-h5-bold">Extrinsics: ${extrinsic.id}</h5>
do we need the $ sign here?

2024-09-03 06:10 UTC, DimitarTAtanasov requested changes

2024-09-03 07:13 UTC, Denis-Dinkov commented on src/components/chainDataList/index.tsx
Absolutely, I will fix it in another PR because it involves a lot of changes.

2024-09-03 07:14 UTC, DimitarTAtanasov approved these changes

2024-09-03 07:16 UTC, merged