[Fix] Explorer page
LimeChain/polkadot-devground-client pull request #56
Opened 2024-09-03 10:33 UTC by Denis-Dinkov

2024-09-03 12:00 UTC, DimitarTAtanasov requested changes

2024-09-03 12:55 UTC, Denis-Dinkov commented on src/views/explorer/components/chainDataList.tsx
Done

2024-09-03 13:02 UTC, Denis-Dinkov commented on src/types/block.ts
> +  signer: unknown;
Done

2024-09-04 11:07 UTC, DimitarTAtanasov approved these changes

2024-09-04 11:32 UTC, merged