Onboarding page
LimeChain/polkadot-devground-client pull request #78
Opened 2024-10-02 07:06 UTC by Denis-Dinkov

2024-10-02 08:03 UTC, pivanov requested changes

2024-10-02 08:03 UTC, pivanov commented on src/views/onboarding/index.tsx
> +      </Tabs >
` >` 🤣

2024-10-02 08:03 UTC, pivanov commented on src/views/onboarding/index.tsx
> +export default Onboarding;
yeah ... here the default export is correct ... because this one is used un routes with lazy import ;)

2024-10-03 09:49 UTC, pivanov commented on src/views/onboarding/components/githubExamples/index.tsx
> +    <div>
we don't need this extra div here ... and we don't need GithubExamples component at all if we use it only to add this extra div here

2024-10-03 09:49 UTC, pivanov commented on src/views/onboarding/components/defaultExamples/index.tsx
> +  }, []);
What do you think?

```suggestion
const [
    filteredSnippets,
    setFilteredSnippets,
  ] = useState(snippets);

  const handleSearch = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const query = e.target.value;
    const filtered = snippets.filter((snippet) =>
      snippet.name.toLowerCase().includes(query.toLowerCase()),
    );
    setFilteredSnippets(filtered);
  }, []);
  ```

2024-10-03 10:45 UTC, Denis-Dinkov commented on src/views/onboarding/components/defaultExamples/index.tsx
> +  }, []);
Nice one :)

2024-10-03 14:33 UTC, pivanov approved these changes
r+

2024-10-03 14:35 UTC, merged