Responsive design and UI changes
LimeChain/polkadot-devground-client pull request #81
Opened 2024-10-03 19:38 UTC by Denis-Dinkov

2024-10-04 06:50 UTC, pivanov requested changes
let's fix these first and we will check it latter deeply

2024-10-04 06:50 UTC, pivanov commented on src/assets/images/icons/icon/pc.svg
can we add it with 24x24 size?

2024-10-04 06:50 UTC, pivanov commented on src/components/burgerMenu/index.tsx
> +  useEventBus<IEventBusClickLink>('@@-click-link', () => {
`@@-click-link` is to generic

2024-10-04 06:50 UTC, pivanov commented on src/components/mobileChainSelect/index.tsx
> +};
map => filter ... we can use for loop or reduce

2024-10-04 06:50 UTC, pivanov commented on src/components/mobileChainSelect/index.tsx
> +            Array.from(filteredGroups) && filteredGroups.length > 0
that expression is redundant and unnecessary

2024-10-04 06:50 UTC, pivanov commented on src/components/navigation/navigationDropdown.tsx
> +  }, []);
check already created hook `useOnClickOutside`

2024-10-04 06:50 UTC, pivanov commented on src/components/navigation/navigationItem.tsx
> +    busDispatch<IEventBusClickLink>({ type: '@@-click-link', data: 'Hello World!' });
to generic as I mention above

2024-10-04 06:50 UTC, pivanov commented on src/hooks/useResponsive.ts
first ... we have `utils/hooks` I've missed that we use `./src/hooks` we should use utils/hooks

2024-10-04 06:50 UTC, pivanov commented on src/hooks/useResponsive.ts
> +      setIsDesktop(width >= breakpoints.tablet);
use one setState we don't need to have 3 or more later

2024-10-04 08:06 UTC, Denis-Dinkov commented on src/components/navigation/navigationDropdown.tsx
> +  }, []);
Done

2024-10-08 07:33 UTC, pivanov approved these changes
r+

2024-10-08 07:41 UTC, merged